### ISSUE TITLE
Post Component 

### ISSUE THREAD

**Issue by KennaReed** [KennaReed/GetInvolved-CalPoly#1]
Creating Schema and creating a general case for a post. 
- Name
- Date Posted
- Date of Event (if relevant) 
- Context 
- Categories [] --- Drop down maybe

Estimated Time: 4
Completion Time: 8 Hours

**Comment by KennaReed** [comment]
4 Story Points

**Comment by areed08** [comment]
I spent 8-10 hours on this but most of that time was because I didn't know what I was doing.
